(deftheme rose-pine-dawn
  "Rose pine dawn, pastel color scheme light variant")

(let ((base    "#faf4ed")
      (surface "#fffaf3")
      (overlay "#f2e9e1")
      (muted   "#9893a5")
      (subtle  "#797593")
      (text    "#575279")
      (love    "#b4637a")
      (gold    "#ea9d34")
      (rose    "#d7827e")
      (pine    "#286983")
      (foam    "#56949f")
      (iris    "#907aa9")
      (hl-low  "#f4ede8")
      (hl-med  "#dfdad9")
      (hl-high "#cecacd"))

    (custom-theme-set-faces
     'rose-pine-dawn
     `(default                          ((t (:foreground ,text :background ,base))))
     `(cursor                           ((t (:background ,iris))))
     `(hl-line                          ((t (:inherit t :background ,hl-low))))
     `(fringe                           ((t (:background ,base))))
     `(highlight                        ((t (:background ,hl-low))))
     `(error                            ((t (:foreground ,love))))
     `(warning                          ((t (:foreground ,rose))))
     `(success                          ((t (:foreground ,foam))))

     `(minibuffer-prompt                ((t (:foreground ,foam))))
     `(link                             ((t (:foreground ,foam :underline t))))
     `(link-visited                     ((t (:foreground ,iris :underline t))))

     `(region                           ((t (:background ,hl-med))))
     `(show-paren-match                 ((t (:underline t))))
     `(show-paren-match-expression      ((t (:background ,hl-med))))
     `(show-paren-mismatch              ((t (:background ,hl-med))))
     
     ;; Line numbers
     `(line-number                      ((t (:foreground ,muted :background ,hl-low))))
     `(line-number-current-line         ((t (:foreground ,iris :background ,hl-low))))

     ;; Windows dividers
     `(window-divider                   ((t (:foreground ,base :background ,base))))
     `(window-divider-first-pixel       ((t (:foreground ,base :background ,base))))
     `(window-divider-last-pixel        ((t (:foreground ,base :background ,base))))

     ;; Font locks
     `(font-lock-warning-face           ((t (:foreground ,love))))
     `(font-lock-function-name-face     ((t (:foreground ,rose))))
     `(font-lock-function-call-face     ((t (:foreground ,rose))))
     `(font-lock-variable-name-face     ((t (:foreground ,text))))
     `(font-lock-variable-use-face      ((t (:foreground ,text))))
     `(font-lock-keyword-face           ((t (:foreground ,pine))))
     `(font-lock-comment-face           ((t (:foreground ,muted))))
     `(font-lock-comment-delimiter-face ((t (:foreground ,muted))))
     `(font-lock-type-face              ((t (:foreground ,foam))))
     `(font-lock-constant-face          ((t (:foreground ,foam))))
     `(font-lock-builtin-face           ((t (:foreground ,love))))
     `(font-lock-preprocessor-face      ((t (:foreground ,love))))
     `(font-lock-string-face            ((t (:foreground ,gold))))
     `(font-lock-doc-face               ((t (:foreground ,gold))))
     `(font-lock-doc-markup-face        ((t (:foreground ,foam))))
     `(font-lock-negation-char-face     ((t (:foreground ,love))))
     `(font-lock-scape-face             ((t (:foreground ,love))))
     `(font-lock-number-face            ((t (:foreground ,rose))))
     `(font-lock-operator-face          ((t (:foreground ,subtle))))
     `(font-lock-punctuation-face       ((t (:foreground ,subtle))))
     `(font-lock-delimiter-face         ((t (:foreground ,rose))))
     `(font-lock-property-name-face     ((t (:foreground ,foam))))
     `(font-lock-property-use-face      ((t (:foreground ,foam))))
     `(font-lock-misc-punctuation-face  ((t (:foreground ,iris))))

     `(sh-quoted-exec                   ((t (:foreground ,love))))
     
     ;; VTerm mode
     `(vterm-color-black          ((t (:foreground ,muted))))
     `(vterm-color-red            ((t (:foreground ,love))))
     `(vterm-color-green          ((t (:foreground ,pine))))
     `(vterm-color-yellow         ((t (:foreground ,gold))))
     `(vterm-color-blue           ((t (:foreground ,foam))))
     `(vterm-color-magenta        ((t (:foreground ,iris))))
     `(vterm-color-cyan           ((t (:foreground ,rose))))
     `(vterm-color-white          ((t (:foreground ,text))))
     `(vterm-color-bright-black   ((t (:foreground ,muted))))
     `(vterm-color-bright-red     ((t (:foreground ,love))))
     `(vterm-color-bright-green   ((t (:foreground ,pine))))
     `(vterm-color-bright-yellow  ((t (:foreground ,gold))))
     `(vterm-color-bright-blue    ((t (:foreground ,foam))))
     `(vterm-color-bright-magenta ((t (:foreground ,iris))))
     `(vterm-color-bright-cyan    ((t (:foreground ,rose))))
     `(vterm-color-bright-white   ((t (:foreground ,text))))

     ;; Rainbow delimiters mode
     `(rainbow-delimiters-depth-1-face    ((t (:foreground ,pine))))
     `(rainbow-delimiters-depth-2-face    ((t (:foreground ,love))))
     `(rainbow-delimiters-depth-3-face    ((t (:foreground ,iris))))
     `(rainbow-delimiters-depth-4-face    ((t (:foreground ,gold))))
     `(rainbow-delimiters-depth-5-face    ((t (:foreground ,foam))))
     `(rainbow-delimiters-depth-6-face    ((t (:foreground ,pine))))
     `(rainbow-delimiters-depth-7-face    ((t (:foreground ,love))))
     `(rainbow-delimiters-depth-8-face    ((t (:foreground ,iris))))
     `(rainbow-delimiters-depth-9-face    ((t (:foreground ,foam))))
     `(rainbow-delimiters-unmatched-face  ((t (:foreground ,muted))))
     `(rainbow-delimiters-mismatched-face ((t (:foreground ,love))))

     ;; Dired full color
     `(diredfl-dir-priv    ((t (:background ,base :foreground ,pine))))
     `(diredfl-read-priv   ((t (:background ,base :foreground ,gold))))
     `(diredfl-write-priv  ((t (:background ,base :foreground ,love))))
     `(diredfl-exec-priv   ((t (:background ,base :foreground ,pine))))
     `(diredfl-no-priv     ((t (:background ,base :foreground ,muted))))
     `(diredfl-date-time   ((t (:background ,base :foreground ,foam))))
     `(diredfl-dir-heading ((t (:background ,base :foreground ,text))))
     `(diredfl-dir-name    ((t (:background ,base :foreground ,pine))))
     `(diredfl-file-name   ((t (:background ,base :foreground ,text))))
     `(diredfl-file-suffix ((t (:background ,base :foreground ,text))))
     `(diredfl-number      ((t (:background ,base :foreground ,foam))))

     ;; Org Mode Faces
     `(variable-pitch ((t (:foreground ,text))))
     `(fixed-pitch    ((t (:foreground ,text))))

     `(org-level-8 ((t (:foreground ,rose))))
     `(org-level-7 ((t (:foreground ,gold))))
     `(org-level-6 ((t (:foreground ,gold))))
     `(org-level-5 ((t (:foreground ,text))))
     `(org-level-4 ((t (:foreground ,text))))
     `(org-level-3 ((t (:foreground ,rose))))
     `(org-level-2 ((t (:foreground ,iris))))
     `(org-level-1 ((t (:foreground ,love))))
     
     `(org-document-title        ((t (:foreground ,text))))
     `(org-block                 ((t (:inherit fixed-pitch :background ,hl-low))))
     `(org-code                  ((t (:inherit (shadow fixed-pitch)))))
     `(org-document-info         ((t (:foreground ,muted ))))
     `(org-document-info-keyword ((t (:inherit (shadow fixed-pitch)))))
     `(org-indent                ((t (:inherit (org-hide fixed-pitch)))))
     `(org-link                  ((t (:foreground ,iris))))
     `(org-meta-line             ((t (:inherit (font-lock-comment-face fixed-pitch)))))
     `(org-property-value        ((t (:inherit fixed-pitch))) t)
     `(org-special-keyword       ((t (:inherit (font-lock-comment-face fixed-pitch)))))
     `(org-table                 ((t (:inherit fixed-pitch :foreground ,subtle)))) 
     `(org-verbatim              ((t (:inherit (shadow fixed-pitch) :foreground ,foam))))
     `(org-drawer                ((t (:inherit fixed-pitch :foreground ,muted))))
     `(org-hide                  ((t (:inherit fixed-pitch :foreground ,base))))
     `(org-tag                   ((t (:foreground ,muted))))
     `(org-todo                  ((t (:foreground ,love))))
     `(org-done                  ((t (:foreground ,muted))))
     `(org-date                  ((t (:foreground ,muted))))

     `(org-agenda-calendar-daterange ((t (:foreground ,text))))
     `(org-agenda-calendar-event     ((t (:foreground ,text))))
     `(org-agenda-calendar-sexp      ((t (:foreground ,text))))
     `(org-agenda-clocking           ((t (:foreground ,text))))
     `(org-agenda-column-dateline    ((t (:foreground ,text))))
     `(org-agenda-current-time       ((t (:foreground ,text))))
     `(org-agenda-date               ((t (:foreground ,foam)))) 
     `(org-agenda-date-today         ((t (:foreground ,pine))))
     `(org-agenda-date-weekend       ((t (:foreground ,pine))))
     `(org-agenda-date-weekend-today ((t (:foreground ,text))))
     `(org-agenda-diary              ((t (:foreground ,text))))
     `(org-agenda-dimmed-todo-face   ((t (:foreground ,text))))
     `(org-agenda-done               ((t (:foreground ,muted))))
     `(org-agenda-filter-category    ((t (:foreground ,text))))
     `(org-agenda-filter-effort      ((t (:foreground ,text))))
     `(org-agenda-filter-regexp      ((t (:foreground ,text))))
     `(org-agenda-filter-tags        ((t (:foreground ,text))))
     `(org-agenda-restriction-lock   ((t (:foreground ,text))))
     `(org-agenda-structure          ((t (:foreground ,text)))) 
     `(org-agenda-structure-filter   ((t (:foreground ,love))))
     `(org-agenda-structure-secondar ((t (:foreground ,text))))
     `(org-scheduled                 ((t (:foreground ,text))))
     `(org-scheduled-previously      ((t (:foreground ,iris))))
     `(org-scheduled-today           ((t (:foreground ,text))))
     `(org-imminent-deadline         ((t (:foreground ,love))))
     `(org-upcoming-deadline         ((t (:foreground ,love))))
     `(org-upcoming-distant-deadline ((t (:foreground ,rose))))
     `(org-time-grid                 ((t (:foreground ,gold))))
     `(org-priority                  ((t (:foreground ,pine))))))

(provide-theme 'rose-pine-dawn)
(provide 'rose-pine-dawn-theme)
