(deftheme rose-pine
  "Rose pine dawn, pastel color scheme light variant")

(let
    ;; ((base    "#191724")
    ;;  (surface "#1f1d2e")
    ;;  (overlay "#26233a")
    ;;  (muted   "#6e6a86")
    ;;  (subtle  "#908caa")
    ;;  (text    "#e0def4")
    ;;  (love    "#eb6f92")
    ;;  (gold    "#f6c177")
    ;;  (rose    "#ebbcba")
    ;;  (pine    "#31748f")
    ;;  (foam    "#9ccfd8")
    ;;  (iris    "#c4a7e7")
    ;;  (hl-low  "#21202e")
    ;;  (hl-med  "#403d52")
    ;;  (hl-high "#524f67"))

    ((hl-high          "#524f67")
     (hl-med           "#403d52")
     (hl-low           "#21202E")
     (iris             "#c4a7e7")
     (foam             "#9ccfd8")
     (foam-low         "#272B37")
     (pine             "#31748f")
     (rose             "#ebbcba")
     (rose-low         "#302935")
     (gold             "#f6c177")
     (gold-low         "#312A2E")
     (love             "#eb6f92")
     (text             "#e0def4")
     (subtle           "#908caa")
     (muted            "#6e6a86")
     (overlay          "#26233a")
     (surface          "#1F1D2E")
     (base             "#191724")
     (ex               "#16141f"))
    
    (custom-theme-set-faces
     'rose-pine
     `(default     ((t (:foreground ,text :background ,surface))))
     `(cursor      ((t (:background ,gold))))
     `(hl-line     ((t (:inherit t :background ,hl-low))))
     `(fringe      ((t (:background ,base))))
     `(highlight   ((t (:background ,hl-low))))
     `(warning     ((t (:foreground ,gold))))
     `(italic      ((t (:foreground ,iris))))

     `(minibuffer-prompt                ((t (:foreground ,foam))))
     `(link                             ((t (:foreground ,foam :underline t))))
     `(link-visited                     ((t (:foreground ,iris :underline t))))

     `(region                           ((t (:background ,hl-med))))
     `(show-paren-match                 ((t (:background ,hl-med))))
     `(show-paren-match-expression      ((t (:background ,hl-med))))
     `(show-paren-mismatch              ((t (:background ,hl-med))))
     
     ;; Line numbers
     `(line-number  ((t (:foreground ,muted :background ,hl-low :weight light
				     :slant italic))))
     `(line-number-current-line ((t (:foreground ,iris :background ,hl-low))))

     ;; Windows dividers
     `(window-divider                   ((t (:foreground ,surface :background ,surface))))
     `(window-divider-first-pixel       ((t (:foreground ,surface :background ,surface))))
     `(window-divider-last-pixel        ((t (:foreground ,surface :background ,surface))))

     ;; Mode line
     `(mode-line          ((t (:foreground ,text :background ,overlay))))
     `(mode-line-active   ((t (:foreground ,text :background ,overlay))))
     `(mode-line-inactive ((t (:foreground ,text :background ,overlay))))     

     ;; Font locks
     `(font-lock-warning-face           ((t (:foreground ,gold  ))))
     `(font-lock-function-name-face     ((t (:foreground ,pine   ))))
     `(font-lock-function-call-face     ((t (:foreground ,rose   ))))
     `(font-lock-variable-name-face     ((t (:foreground ,text   ))))
     `(font-lock-variable-use-face      ((t (:foreground ,text   ))))
     `(font-lock-keyword-face           ((t (:foreground ,iris   ))))
     `(font-lock-comment-face           ((t (:foreground ,muted  ))))
     `(font-lock-comment-delimiter-face ((t (:foreground ,muted  ))))
     `(font-lock-type-face              ((t (:foreground ,foam   ))))
     `(font-lock-constant-face          ((t (:foreground ,rose   ))))
     `(font-lock-builtin-face           ((t (:foreground ,pine   ))))
     `(font-lock-preprocessor-face      ((t (:foreground ,love   ))))
     `(font-lock-string-face            ((t (:foreground ,gold   ))))
     `(font-lock-doc-face               ((t (:foreground ,muted   ))))
     `(font-lock-doc-markup-face        ((t (:foreground ,foam   ))))
     `(font-lock-negation-char-face     ((t (:foreground ,love   ))))
     `(font-lock-scape-face             ((t (:foreground ,love   ))))
     `(font-lock-number-face            ((t (:foreground ,rose   ))))
     `(font-lock-operator-face          ((t (:foreground ,subtle ))))
     `(font-lock-punctuation-face       ((t (:foreground ,subtle ))))
     `(font-lock-delimiter-face         ((t (:foreground ,rose   ))))
     `(font-lock-property-name-face     ((t (:foreground ,foam   ))))
     `(font-lock-property-use-face      ((t (:foreground ,foam   ))))
     `(font-lock-misc-punctuation-face  ((t (:foreground ,iris   ))))

     `(sh-quoted-exec                   ((t (:foreground ,love))))
     
     ;; VTerm mode
     `(vterm-color-black          ((t (:foreground ,muted))))
     `(vterm-color-red            ((t (:foreground ,love))))
     `(vterm-color-green          ((t (:foreground ,pine))))
     `(vterm-color-yellow         ((t (:foreground ,gold))))
     `(vterm-color-blue           ((t (:foreground ,foam))))
     `(vterm-color-magenta        ((t (:foreground ,iris))))
     `(vterm-color-cyan           ((t (:foreground ,rose))))
     `(vterm-color-white          ((t (:foreground ,text))))
     `(vterm-color-bright-black   ((t (:foreground ,muted))))
     `(vterm-color-bright-red     ((t (:foreground ,love))))
     `(vterm-color-bright-green   ((t (:foreground ,pine))))
     `(vterm-color-bright-yellow  ((t (:foreground ,gold))))
     `(vterm-color-bright-blue    ((t (:foreground ,foam))))
     `(vterm-color-bright-magenta ((t (:foreground ,iris))))
     `(vterm-color-bright-cyan    ((t (:foreground ,rose))))
     `(vterm-color-bright-white   ((t (:foreground ,text))))

     ;; Rainbow delimiters mode
     `(rainbow-delimiters-depth-1-face    ((t (:foreground ,iris ))))
     `(rainbow-delimiters-depth-2-face    ((t (:foreground ,rose ))))
     `(rainbow-delimiters-depth-3-face    ((t (:foreground ,foam ))))
     `(rainbow-delimiters-depth-4-face    ((t (:foreground ,gold ))))
     `(rainbow-delimiters-depth-5-face    ((t (:foreground ,love ))))
     `(rainbow-delimiters-depth-6-face    ((t (:foreground ,pine ))))
     `(rainbow-delimiters-depth-7-face    ((t (:foreground ,iris ))))
     `(rainbow-delimiters-depth-8-face    ((t (:foreground ,foam ))))
     `(rainbow-delimiters-depth-9-face    ((t (:foreground ,rose ))))
     `(rainbow-delimiters-unmatched-face  ((t (:foreground ,muted))))
     `(rainbow-delimiters-mismatched-face ((t (:foreground ,love ))))

     ;; Dired full color
     `(diredfl-dir-priv    ((t (:background ,base :foreground ,pine  ))))
     `(diredfl-read-priv   ((t (:background ,base :foreground ,gold  ))))
     `(diredfl-write-priv  ((t (:background ,base :foreground ,love  ))))
     `(diredfl-exec-priv   ((t (:background ,base :foreground ,pine  ))))
     `(diredfl-no-priv     ((t (:background ,base :foreground ,muted ))))
     `(diredfl-date-time   ((t (:background ,base :foreground ,foam  ))))
     `(diredfl-dir-heading ((t (:background ,base :foreground ,text   ))))
     `(diredfl-dir-name    ((t (:background ,base :foreground ,pine  ))))
     `(diredfl-file-name   ((t (:background ,base :foreground ,text  ))))
     `(diredfl-file-suffix ((t (:background ,base :foreground ,text  ))))
     `(diredfl-number      ((t (:background ,base :foreground ,foam  t))))

     ;; Org Mode Faces
     `(variable-pitch ((t (:background ,text))))
     `(fixed-pitch    ((t (:background ,text))))

     `(org-level-8 ((t (:foreground ,text))))
     `(org-level-7 ((t (:foreground ,text))))
     `(org-level-6 ((t (:foreground ,text))))
     `(org-level-5 ((t (:foreground ,text))))
     `(org-level-4 ((t (:foreground ,text))))
     `(org-level-3 ((t (:foreground ,text))))
     `(org-level-2 ((t (:foreground ,text))))
     `(org-level-1 ((t (:foreground ,text))))
     
     `(org-document-title        ((t (:underline nil))))
     `(org-block                 ((t (:inherit fixed-pitch :background ,hl-low))))
     `(org-code                  ((t (:inherit (shadow fixed-pitch)))))
     `(org-document-info         ((t (:foreground ,muted ))))
     `(org-document-info-keyword ((t (:inherit (shadow fixed-pitch)))))
     `(org-indent                ((t (:inherit (org-hide fixed-pitch)))))
     `(org-link                  ((t (:foreground ,iris :underline t))))
     `(org-meta-line             ((t (:inherit (font-lock-comment-face fixed-pitch)))))
     `(org-property-value        ((t (:inherit fixed-pitch))) t)
     `(org-special-keyword       ((t (:inherit (font-lock-comment-face fixed-pitch)))))
     `(org-table                 ((t (:inherit fixed-pitch :foreground ,subtle)))) 
     `(org-verbatim              ((t (:inherit (shadow fixed-pitch) :foreground ,foam))))
     `(org-drawer                ((t (:inherit fixed-pitch :foreground ,muted))))
     `(org-hide                  ((t (:inherit fixed-pitch :foreground ,base))))
     `(org-tag                   ((t (:foreground ,muted :weight regular ))))
     `(org-todo                  ((t (:foreground ,love :weight bold))))
     `(org-done                  ((t (:foreground ,muted :weight bold))))
     `(org-date                  ((t (:foreground ,muted :weight light :underline nil))))

     `(org-agenda-calendar-daterange ((t (:foreground ,text :weight regular))))
     `(org-agenda-calendar-event     ((t (:foreground ,text :weight regular))))
     `(org-agenda-calendar-sexp      ((t (:foreground ,text :weight regular))))
     `(org-agenda-clocking           ((t (:foreground ,text :weight regular))))
     `(org-agenda-column-dateline    ((t (:foreground ,text :weight regular))))
     `(org-agenda-current-time       ((t (:foreground ,text :weight regular))))
     `(org-agenda-date               ((t (:foreground ,foam :weight light :slant normal)))) 
     `(org-agenda-date-today         ((t (:foreground ,pine :weight bold :slant italic))))
     `(org-agenda-date-weekend       ((t (:foreground ,pine :weight bold :slant italic))))
     `(org-agenda-date-weekend-today ((t (:foreground ,text :weight regular))))
     `(org-agenda-diary              ((t (:foreground ,text :weight regular))))
     `(org-agenda-dimmed-todo-face   ((t (:foreground ,text :weight regular))))
     `(org-agenda-done               ((t (:foreground ,muted :weight light))))
     `(org-agenda-filter-category    ((t (:foreground ,text :weight regular))))
     `(org-agenda-filter-effort      ((t (:foreground ,text :weight regular))))
     `(org-agenda-filter-regexp      ((t (:foreground ,text :weight regular))))
     `(org-agenda-filter-tags        ((t (:foreground ,text :weight regular))))
     `(org-agenda-restriction-lock   ((t (:foreground ,text :weight regular))))
     `(org-agenda-structure          ((t (:foreground ,text :weight bold :slant italic)))) 
     `(org-agenda-structure-filter   ((t (:foreground ,love :weight light :slant italic))))
     `(org-agenda-structure-secondar ((t (:foreground ,text :weight regular))))
     `(org-scheduled                 ((t (:foreground ,text :weight light))))
     `(org-scheduled-previously      ((t (:foreground ,iris :weight light))))
     `(org-scheduled-today           ((t (:foreground ,text :weight light))))
     `(org-imminent-deadline         ((t (:foreground ,love :weight light))))
     `(org-upcoming-deadline         ((t (:foreground ,love :weight light))))
     `(org-upcoming-distant-deadline ((t (:foreground ,rose :weight light))))
     `(org-time-grid                 ((t (:foreground ,gold :weight light))))
     `(org-priority                  ((t (:foreground ,pine :weight regular)))))

    (setq mono-modeline-background-color base
	  mono-modeline-name-color       text
	  mono-modeline-right-color      muted
	  mono-modeline-icon-RW-color    gold
	  mono-modeline-icon-**-color    love
	  mono-modeline-icon-RO-color    foam
	  mono-modeline-i-color          muted))


(provide-theme 'rose-pine)
(provide 'rose-pine-theme)
